# Generated by Django 2.2.5 on 2020-01-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgae',
            new_name='image',
        ),
    ]
