# Generated by Django 3.1.4 on 2020-12-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mails',
        ),
    ]
